### ISSUE TITLE
Update tests

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-storage-js#2]
@jcnelson can you help me update the tests in the repo so that they pass? Right now they’re failing on CircleCI.

**Comment by jcnelson** [comment]
It's probably because we need to merge `develop-jude` from `blockstack.js` to `master`, so `npm install` will grab the right package.

**Comment by jcnelson** [comment]
Sure; working on this

**Comment by jcnelson** [comment]
Fixed!

**Comment by larrysalibra** [comment]
@jcnelson

**Comment by larrysalibra** [comment]
Tests are passing finally!
