### ISSUE TITLE
require('node-localstorage') breaks webpack

### ISSUE THREAD

**Issue by larrysalibra** [blockstack/blockstack-storage-js#4]
We can't use this module in webpack apps as is because it requires `node-localstorage` (for testing). 

Webpack tries to import all requires even ones that conditionally won't be executed because we're in the browser.

My attempt at fixing this by moving the module to runtime dependencies didn't work.

https://github.com/blockstack/blockstack-storage-js/commit/cde11db7ff88fc0a8e7466624b31687f76a6fcbe

**Comment by larrysalibra** [comment]
```
 ERROR  Failed to compile with 1 errors                                                                     7:23:18 PM

This dependency was not found:

* node-localstorage in ./~/blockstack-storage/lib/datastore.js
```

**Comment by jcnelson** [comment]
Is there some other mechanism we can use?  I need localStorage to work in node.js.

**Comment by larrysalibra** [comment]
We can probably mock localstorage if it doesn't exist. That's what I'd assume node-localstorage would do, but apparently it doesn't.

**Comment by larrysalibra** [comment]
I've mocked local storage in this commit https://github.com/blockstack/blockstack-storage-js/commit/be2088c95ea0182b4e05ad47beb9bf84a87259bb and the errors about missing localStorage in node seem to have gone away.
