### ISSUE TITLE
Payload does not match inode header (error)

### ISSUE THREAD

**Issue by icidasset** [blockstack/blockstack-storage-js#7]
Hi 👋 

I'm getting the following error when trying store a rather large json string:

> Error: Failed to putFile /ongaku-ryoho-v1_0.json (errno: 22): Payload a051db852f2ed2b9fe66b02ad750572b301d23cf5044cded5be4c6c35d127d08 does not match inode header ea923245d45c0c2b0f88c0fbb11f01e8639499a1be3565a2f0443a5e4d0abfd0

Works fine for smaller strings though 🤔 
Here's the json: https://gist.github.com/icidasset/79df55b34eb4de6fbde2da617f0cd709
(not the exact thing I used because I had to remove some sensitive data)

Not sure where to go from here.
Any suggestions?
Thanks!

**Comment by larrysalibra** [comment]
Sorry to hear that @icidasset. 

@jcnelson or @kantai should be able to shed some light on why that's happening

**Comment by kantai** [comment]
Looks like a unicode issue in our JS library's interaction with Core. Working on a fix now!

**Comment by icidasset** [comment]
It appears to work now, thanks for fixing this! 😄 
You can close this if you think this is resolved.

**Comment by larrysalibra** [comment]
@icidasset are you using this library directly or via https://github.com/blockstack/blockstack.js?

**Comment by icidasset** [comment]
@larrysalibra I'm using this library directly (master branch, not npm release)

**Comment by kantai** [comment]
Addressed in commit 28b53605
